#baseURL = 'https://graphics.cg.uni-saarland.de/vcc'
languageCode = 'en-us'
title = 'Vcc - the Vulkan Clang Compiler'
theme='hugo-book'

[markup.goldmark.renderer]
  unsafe = true

[params]
  BookSection = "*"